name: GitHub Action CI

on:
    pull_request:
        # We don't need this to be run on all types of PR behavior
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
        types:
          - opened
          - synchronize
          - edited

jobs:
  mpi4py:
    name: mpi4py sanity checks
    runs-on: ubuntu-latest
    steps:
    - name: Install depencencies
      run:  sudo apt-get install -y -q
              libnuma-dev

    - name: Check out the code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Bootstrap Open MPI
      run:  ./autogen.pl

    - name: Configure Open MPI
      run:  ./configure
              --disable-dependency-tracking
              --enable-debug
              --enable-mem-debug
              --disable-man-pages
              --disable-mpi-fortran
              LDFLAGS=-Wl,-rpath,/usr/local/lib

    - name: Build Open MPI
      run:  make -j 2

    - name: Install Open MPI
      run:  sudo make install

    - name: Show Open MPI
      run:  ompi_info

    - name: Show MPICC
      run:  mpicc -show

    - name: Use Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Python packages
      run:  python -m pip install --upgrade
              setuptools pip wheel
              numpy cffi simplejson PyYAML

    - name: Checkout mpi4py
      uses: actions/checkout@v2
      with:
        repository: mpi4py/mpi4py
        ref:        master
        path:       mpi4py

    - name: Install mpi4py
      run:  python -m pip install ./mpi4py
      env:
        CFLAGS: '-O0'

    - name: Test mpi4py (np=1)
      run:  mpiexec -n 1 python mpi4py/test/runtests.py -v
    - name: Test mpi4py (np=2)
      run:  mpiexec -n 2 python mpi4py/test/runtests.py -v -f
    - name: Test mpi4py (np=3)
      run:  mpiexec -n 3 python mpi4py/test/runtests.py -v -f

    - name: Test mpi4py.futures (np=1)
      run:  mpiexec -n 1 python mpi4py/demo/futures/test_futures.py -v
    - name: Test mpi4py.futures (np=2)
      run:  mpiexec -n 2 python mpi4py/demo/futures/test_futures.py -v
    - name: Test mpi4py.futures (np=3)
      run:  mpiexec -n 3 python mpi4py/demo/futures/test_futures.py -v

    - name: Test mpi4py.futures (np=1)
      run:  mpiexec -n 1 python -m mpi4py.futures mpi4py/demo/futures/test_futures.py -v
    - name: Test mpi4py.futures (np=2)
      run:  mpiexec -n 2 python -m mpi4py.futures mpi4py/demo/futures/test_futures.py -v
    - name: Test mpi4py.futures (np=3)
      run:  mpiexec -n 3 python -m mpi4py.futures mpi4py/demo/futures/test_futures.py -v
