name: Reusable workflow testing

on:
  workflow_call:

jobs:
  entrypoint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: say hello
        run: |
          echo hello world
          env | grep DO_
