name: Reusable workflow testing

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string

jobs:
  entrypoint:
    runs-on: ubuntu-latest
    env:
      the_value: ${{ inputs.env_name }}
      ${{ inputs.env_name}}: 42
    steps:
      - name: say hello
        run: |
          echo hello world
          echo the input was ${{ inputs.env_name }}
          echo the env var was: $${{ inputs.env_name }}
          cat >file.json <<EOF
          ${{ toJson(github) }}
          EOF
          echo cat file.json
