name: Reusable workflow example

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string

jobs:
  entrypoint:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo hello world
      - name: show the input
        run: echo the input was ${{ inputs.env_name }}
